[build]
  publish = "frontend/build"
  command = "cd frontend && npm run build"

[build.environment]
  REACT_APP_API_URL = "https://your-app-name.up.railway.app"
  REACT_APP_NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
