# Railway configuration
[build]
command = "pip install -r requirements.txt"

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PYTHON_VERSION = "3.9"
